"""Packs the cliff rock texture into src/cliff_texture.inc.

    python art/cliffs/gen_cliff_texture.py

art/cliffs/cliff_texture.aseprite (exported beside it as cliff_texture.png) is
drawn through the pixel plugin from cliff_texture_design.py: a tileable square
of rock in four grey values -- crack, shade, base, lit. The game paints every
cliff wall from it in world coordinates (src/cliff_paint.cpp), swapping the
four values for the island's ore ramp, so only the values are stored here.
"""
import os
import sys

from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
ART = os.path.join(HERE, "cliff_texture.png")
OUT = os.path.join(ROOT, "src", "cliff_texture.inc")
VALUES = {(0, 0, 0): 0, (0x5c, 0x5c, 0x68): 1, (0x8c, 0x8c, 0x98): 2, (0xc4, 0xc4, 0xcc): 3}   # crack, shade, base, lit


def main():
    im = Image.open(ART).convert("RGB")
    n = im.width
    if im.height != n:
        sys.exit("cliff_texture.png must be square, is %dx%d" % (im.width, im.height))
    px = im.load()
    rows = []
    for y in range(n):
        row = []
        for x in range(n):
            if px[x, y] not in VALUES:
                sys.exit("cliff_texture.png has %s at %d,%d, not one of the four values" % (px[x, y], x, y))
            row.append(str(VALUES[px[x, y]]))
        rows.append("    \"" + "".join(row) + "\",")
    text = "\n".join([
        "// Generated by art/cliffs/gen_cliff_texture.py -- do not edit.",
        "// The cliff rock texture: one digit per pixel, 0 crack, 1 shade, 2 base, 3 lit.",
        "enum { CLIFF_TEX_N = %d };" % n,
        "static const char CLIFF_TEX[CLIFF_TEX_N][CLIFF_TEX_N + 1] = {",
    ] + rows + ["};", ""])
    open(OUT, "w", encoding="utf-8", newline="\n").write(text)
    print("wrote", os.path.relpath(OUT, ROOT), "(%dx%d)" % (n, n))


if __name__ == "__main__":
    main()
