"""Design for the item icons (art/items/items.aseprite).

    python art/items/items_design.py <out.json>
    python tools/draw_views.py <out.json> art/items/items     # through the pixel plugin
    python art/items/gen_items.py                             # -> assets/items.png

One 16x16 drawing per kind of icon. The four capitals are the stone key tones
(line, shade, base, lit), swapped by gen_items.py for the ramp each icon is
coloured in -- the ore chunk once per ore, the way the battle shots are. The
lowercase letters are a fixed green (the emerald ramp) for stems and leaves,
left as they are, and p is the palette's white, for pages. Mother 1 style: black outline, flat base, a pixel of shade,
little light.
"""
import json, sys

# line, shade, base, lit: the stone ramp of art/structures/gen_cave_entrances.py;
# s, b, l: the emerald ramp, for green that stays green.
PAL = {'K': '000000', 'S': '474751', 'B': '848694', 'L': 'bcbeca',
       's': '235436', 'b': '4fa667', 'l': 'a8f0bc', 'p': 'fcfcfc'}
ORDER = ['wood', 'ore', 'gold', 'flower', 'gravestone', 'oilbloom',
         'hide', 'bone', 'essence', 'vine', 'raft_book', 'raft',
         'spearhead', 'moon_steel', 'reapers_edge', 'feather', 'sleeping_bag']

def cell(rows):
    """16 rows of 16, padded with transparent."""
    g = [r.ljust(16, '.') for r in rows]
    return g + ['.' * 16] * (16 - len(g))

VIEWS = {
    # a log on its side, the cut end towards you on the right
    'wood': cell(['',
                  '',
                  '',
                  '...KKKKKKKKKK',
                  '..KLLLLLLLLKBKK',
                  '.KBBBBBBBBKBLLBK',
                  '.KBSBBBBSBKLSSLK',
                  '.KBBBBSBBBKLSSLK',
                  '.KBBBBBBBBKBLLBK',
                  '.KSSSSSSSSKSBBSK',
                  '..KKKKKKKKKKKKK']),
    # a broken lump of ore, lit from the top left; one per ore
    'ore': cell(['',
                 '',
                 '......KKKK',
                 '....KKLLLBKK',
                 '...KLLLBBBBKK',
                 '..KLLBBBBBSBBK',
                 '..KLBBBBBSSBBK',
                 '.KLBBBBBBBSBBBK',
                 '.KBBBSBBBBBBBSK',
                 '.KBBSSBBBBBBSSK',
                 '.KSBBBBBBBSSSSK',
                 '..KSSSBBSSSSSK',
                 '...KKKSSSSKKK',
                 '......KKKK']),
    # a coin, a raised rim round its face
    'gold': cell(['',
                  '',
                  '.....KKKKKK',
                  '....KLLLLLBK',
                  '...KLBBBBBBSK',
                  '..KLBLLLLLBBSK',
                  '..KLBLBBBBSBSK',
                  '..KLBLBBBBSBSK',
                  '..KLBLBBBBSBSK',
                  '..KLBBSSSSSBSK',
                  '..KBBBBBBBBBSK',
                  '...KBSSSSSSSK',
                  '....KSSSSSSK',
                  '.....KKKKKK']),
    # four petals round a lit heart, on a green stem
    'flower': cell(['',
                    '.....KKK',
                    '....KLLBK',
                    '..KKKLBBKKK',
                    '.KLLBKBKBLBK',
                    '.KLBBKLKBBSK',
                    '..KKKBBBKKK',
                    '....KBBSK',
                    '.....KKK',
                    '......Ks',
                    '....Kb.bK',
                    '...Kbl.bsK',
                    '....KKbK',
                    '......bs',
                    '......sK']),
    # a rounded headstone with a cross cut in it, on a step of earth
    'gravestone': cell(['',
                        '.....KKKKKK',
                        '....KLLLLLBK',
                        '...KLLBSBBBSK',
                        '...KLBBSBBBSK',
                        '...KLSSSSSBSK',
                        '...KLBBSBBBSK',
                        '...KLBBSBBBSK',
                        '...KLBBBBBBSK',
                        '...KLBBBBBBSK',
                        '...KBBBBBBBSK',
                        '..KKKKKKKKKKKK',
                        '..KsbbbbbbbbsK',
                        '...KKKKKKKKKK']),
    # the rare bloom: a cup of six petals holding a drop of its oil
    'oilbloom': cell(['',
                      '...KK....KK',
                      '..KLBK..KBLK',
                      '..KLBBKKBBLK',
                      '.KKLBBLLBBLKK',
                      'KLLKBLBBLBKLLK',
                      'KLBBKBLLBKBBSK',
                      '.KSBBKLLKBBSK',
                      '..KKSBBBBSKK',
                      '....KKKKKK',
                      '......Ks',
                      '....KbKsbK',
                      '...KblKbsK',
                      '....KK.Kb',
                      '.......bs',
                      '.......sK']),
    # a stretched pelt, its four legs out
    'hide': cell(['',
                  '',
                  '..KK......KK',
                  '.KBBK....KBBK',
                  '..KBBKKKKBBK',
                  '...KLLLLLLBK',
                  '..KLBBBBBBBSK',
                  '..KLBBSBBBBSK',
                  '..KLBBBBBSBSK',
                  '..KLBSBBBBBSK',
                  '...KBBBBBBSK',
                  '..KBBKKKKSBBK',
                  '.KBBK....KBBK',
                  '..KK......KK']),
    # a long bone, knuckled at both ends, laid corner to corner
    'bone': cell(['',
                  '..KK',
                  '.KLLK.',
                  '.KLLBKK',
                  '..KLBLBK',
                  '...KKLBK',
                  '.....KLBK',
                  '......KLBK',
                  '.......KLBK',
                  '........KLBKK',
                  '.........KLBLK',
                  '..........KBLLK',
                  '..........KLLK',
                  '...........KK']),
    # a wisp of essence: a flame-like drop, bright at its core
    'essence': cell(['',
                     '........K',
                     '.......KBK',
                     '......KBLK',
                     '.....KBLBK',
                     '....KBLLBK',
                     '...KBLLLLBK',
                     '...KBLLLLBK',
                     '..KBBLLLLBSK',
                     '..KBBBLLBBSK',
                     '..KSBBBBBSSK',
                     '...KSBBBSSK',
                     '....KSSSSK',
                     '.....KKKK']),
    # a length of vine, curling, a leaf at each turn
    'vine': cell(['',
                  '..........KK',
                  '.........KLBK',
                  '........KBLBK',
                  '....KK.KSBK',
                  '...KLBKKBK',
                  '...KBLBKBK',
                  '....KKKBK',
                  '.......KBK',
                  '......KBK.KK',
                  '......KBKKLBK',
                  '.....KBK.KBLBK',
                  '.....KBK..KKK',
                  '....KBK',
                  '....KK']),
    # the book that teaches the raft: a leather cover, a raft on its face, white pages
    'raft_book': cell(['',
                       '..KKKKKKKKKKKK',
                       '..KLLLLLLLLLBKK',
                       '..KLBBBBBBBBBKpK',
                       '..KLBKKKKKKBBKpK',
                       '..KLBKLLLLKBBKpK',
                       '..KLBKKKKKKBBKpK',
                       '..KLBKLLLLKBBKpK',
                       '..KLBKKKKKKBBKpK',
                       '..KLBBBBBBBBBKpK',
                       '..KLBBBBBBBBBKpK',
                       '..KSSSSSSSSSSKpK',
                       '...KKKKKKKKKKKKK']),
    # the raft, seen from above: four logs lashed with two bands of vine
    'raft': cell(['',
                  '.KKKKKKKKKKKKKK',
                  'KLLLbLLLLLLbLLLK',
                  'KBBBbBBBBBBbBBSK',
                  'KKKKKKKKKKKKKKKK',
                  'KLLLbLLLLLLbLLLK',
                  'KBBBbBBBBBBbBBSK',
                  'KKKKKKKKKKKKKKKK',
                  'KLLLbLLLLLLbLLLK',
                  'KBBBbBBBBBBbBBSK',
                  'KKKKKKKKKKKKKKKK',
                  'KLLLbLLLLLLbLLLK',
                  'KBBBbBBBBBBbBBSK',
                  '.KKKKKKKKKKKKKK']),
    # the halberd's special part: an old spear point on its socket, found in ruins
    'spearhead': cell(['',
                       '.......KK',
                       '......KLLK',
                       '......KLBK',
                       '.....KLLBSK',
                       '.....KLBBSK',
                       '....KLLBBBSK',
                       '....KLBBBBSK',
                       '....KLBBBSSK',
                       '.....KLBBSK',
                       '......KLSK',
                       '......KBSK',
                       '.....KKSSKK',
                       '.....KBBBSK',
                       '.....KKKKKK']),
    # the katana's: an ingot of moon steel, a crescent struck into its face
    'moon_steel': cell(['',
                        '',
                        '',
                        '',
                        '....KKKKKKKK',
                        '...KLLLLLLLLK',
                        '..KLBBBLLBBBSK',
                        '.KLBBBLBBBBBSSK',
                        '.KLBBLBBBBBBSSK',
                        '.KLBBBLBBBBBSSK',
                        '.KBBBBBLLBBBSSK',
                        '.KSSSSSSSSSSSSK',
                        '..KKKKKKKKKKKK']),
    # the scythe's: a dark curved shard of a reaper's blade, found in catacombs
    'reapers_edge': cell(['',
                          '..........KK',
                          '........KKLLK',
                          '......KKLLBBK',
                          '.....KLLBBBSK',
                          '....KLBBBSSK',
                          '...KLBBSSKK',
                          '...KLBSKK',
                          '..KLBSK',
                          '..KLBSK',
                          '..KLSK',
                          '..KLK',
                          '...KK']),
    # a feather dropped by a bird: a quill corner to corner, its vane wider
    # on the lit side, barbs notched in along it
    'feather': cell(['',
                     '...........KKK',
                     '.........KKLLBK',
                     '........KLLLBSK',
                     '.......KLLLBBSK',
                     '......KLLLBBSK',
                     '.....KLLKBBSSK',
                     '....KLLLBBSSK',
                     '....KLLBBSKK',
                     '...KLLBBSSK',
                     '...KLKBSSK',
                     '..KLBBSKK',
                     '..KBSKK',
                     '.KLKK',
                     'KLK',
                     'KK']),
    # the sleeping bag, rolled up: a leather roll tied with two bands of vine,
    # the rolled end towards you on the right
    'sleeping_bag': cell(['',
                          '',
                          '',
                          '..KKKKKKKKKKK',
                          '.KLLbLLLbLBBBK',
                          '.KLLbLLLbBBSBBK',
                          '.KBBbBBBBBSLSBBK',
                          '.KBBsBBBBSLLLSBK',
                          'KBBBsBBBBSLLLSBK',
                          '.KBBsBBBBSLLLSBK',
                          '.KBBsBBBBBSLSBBK',
                          '.KSSsSSSsBBSBBK',
                          '.KSSsSSSsSBBBK',
                          '..KKKKKKKKKKK']),
}

if __name__ == '__main__':
    json.dump({'pal': PAL, 'view_w': 16, 'order': ORDER, 'views': VIEWS}, open(sys.argv[1], 'w'))
