"""Bake the oasis for the game: the shapes of the user's reference
(tools/oasis_blocks.py) as data, and its art beside the sheet.

    python tools/gen_oasis.py

Writes
    src/oasis.inc         the reference's sprites as solid masks (a bit a rock
                          pixel), the run they lie in -- the reference and its
                          mirror end to end, from its third column, boulders
                          lifted -- and where each art piece sits in
                          assets/oasis.png
    assets/oasis.png      the oasis's pieces (art/structures/dungeon_walls/
                          oasis.png, drawn through the plugin), as they are
    assets/player_swim.png  the swimmer (art/player/swim.png)

The rock itself is not here: the game fills it with the overworld cliffs'
texture (src/cliff_texture.inc), in the oasis's darker olive.
"""
import os, shutil, sys
import numpy as np

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, 'tools'))
import oasis_blocks as ob

VW = 256                                   # oasis_design.py's view width
PIECES = [                                 # name, view, x, y, w, h (pixels within the view)
    ('weed0', 2, 0, 0, 16, 32), ('weed1', 3, 0, 0, 16, 32), ('weed2', 4, 0, 0, 16, 32),
    ('bub0', 5, 0, 0, 3, 3), ('bub1', 5, 5, 0, 5, 5), ('bub2', 5, 12, 0, 7, 7),
    ('surf0', 6, 0, 0, 64, 6), ('surf1', 7, 0, 0, 64, 6), ('surf2', 8, 0, 0, 64, 6),
    ('far', 9, 0, 0, 128, 208), ('ruin', 11, 0, 0, 48, 40), ('hud', 12, 0, 0, 24, 8),
    ('eye0', 13, 0, 0, 16, 8), ('eye1', 14, 0, 0, 16, 8), ('eye2', 15, 0, 0, 16, 8),
    ('levi', 16, 0, 0, 128, 48), ('levi_near', 17, 0, 0, 256, 72), ('shaft', 20, 0, 0, 64, 208),
]


def main():
    sprites, classes, (ref, mir) = ob.vocabulary()
    cls = np.array(classes)
    Wr = ref.shape[1]
    run = np.concatenate([ref[:, 2:], mir[:, :-2]], axis=1)      # as ob.level() lays it
    water_of = {}
    for y in range(ref.shape[0]):
        row = [v for v in ref[y] if cls[v] == ob.WATER]
        if row:
            water_of[y] = max(set(row), key=row.count)
    for y, x in zip(*np.nonzero(cls[run] == ob.BOULDER)):
        run[y, x] = water_of[y]                                   # boulders lifted: open water
    used = sorted(set(run.flatten().tolist()))
    remap = {s: i for i, s in enumerate(used)}
    masks = []
    for s in used:
        t = sprites[s]
        masks.append([sum(1 << x for x in range(16) if t[y][x] != 'W') for y in range(16)])
    H, P = run.shape
    out = ['// Generated by tools/gen_oasis.py -- do not edit.',
           '// The oasis\'s shapes, from the user\'s reference: its sprites as solid masks (bit x',
           '// of row y set where the rock is) and the run they lie in, the reference and its',
           '// mirror end to end, boulders lifted. A level is a stretch of this run.',
           'enum { OASIS_ROWS = %d, OASIS_RUN = %d, OASIS_SPRITES = %d };' % (H, P, len(used)),
           'static const unsigned short OASIS_MASK[OASIS_SPRITES][16] = {']
    for m in masks:
        out.append('    { %s },' % ', '.join('0x%04x' % v for v in m))
    out.append('};')
    out.append('static const unsigned char OASIS_RUN_IDS[OASIS_ROWS][OASIS_RUN] = {')
    for y in range(H):
        out.append('    { %s },' % ', '.join(str(remap[int(v)]) for v in run[y]))
    out.append('};')
    out.append('// The water\'s dot lattice, (x %% 8, y %% 8) of the level\'s art pixels.')
    out.append('static const unsigned char OASIS_DOTS[%d][2] = { %s };' % (
        len(ob.DOTS), ', '.join('{%d, %d}' % d for d in sorted(ob.DOTS))))
    out.append('// The pieces in assets/oasis.png: x, y, w, h.')
    out.append('enum OasisPiece { %s, OASIS_PIECES };' % ', '.join('OP_' + n.upper() for n, *_ in PIECES))
    out.append('static const short OASIS_PIECE[OASIS_PIECES][4] = {')
    for n, v, x, y, w, h in PIECES:
        out.append('    { %d, %d, %d, %d },   // %s' % (v * VW + x, y, w, h, n))
    out.append('};')
    open(os.path.join(ROOT, 'src', 'oasis.inc'), 'w', newline='\n').write('\n'.join(out) + '\n')
    shutil.copyfile(os.path.join(ROOT, 'art', 'structures', 'dungeon_walls', 'oasis.png'),
                    os.path.join(ROOT, 'assets', 'oasis.png'))
    shutil.copyfile(os.path.join(ROOT, 'art', 'player', 'swim.png'),
                    os.path.join(ROOT, 'assets', 'player_swim.png'))
    print('oasis: %d sprites, run %d x %d, %d pieces' % (len(used), H, P, len(PIECES)))


if __name__ == '__main__':
    main()
