#include "fc_palette.h"

#include <stdlib.h>

// Generated by tools/palette_pass.py --write:
//   FC_PALETTE[FC_PALETTE_N][3]    the palette
//   FC_EXACT[FC_EXACT_N]           rgb24 << 8 | index, sorted: every palette
//                                  colour and every colour fcremap.REMAP names,
//                                  answered exactly
//   FC_LUT[32768]                  index for any other colour, by its top five
//                                  bits a channel: fcremap's nearest-colour rule
//                                  run on each bucket's centre
#include "fc_palette_lut.inc"

static int cmp_exact(const void* key, const void* e) {
    uint32_t k = *(const uint32_t*)key, v = *(const uint32_t*)e >> 8;
    return k < v ? -1 : k > v ? 1 : 0;
}

SDL_Color fc_snap(uint8_t r, uint8_t g, uint8_t b) {
    uint32_t rgb = ((uint32_t)r << 16) | ((uint32_t)g << 8) | b;
    const uint32_t* hit = (const uint32_t*)bsearch(&rgb, FC_EXACT, FC_EXACT_N,
                                                   sizeof FC_EXACT[0], cmp_exact);
    int i = hit ? (int)(*hit & 0xFF) : FC_LUT[((r >> 3) << 10) | ((g >> 3) << 5) | (b >> 3)];
    SDL_Color c = { FC_PALETTE[i][0], FC_PALETTE[i][1], FC_PALETTE[i][2], 255 };
    return c;
}

int fc_draw_color(SDL_Renderer* ren, uint8_t r, uint8_t g, uint8_t b, uint8_t a) {
    SDL_Color c = fc_snap(r, g, b);
    return SDL_SetRenderDrawColor(ren, c.r, c.g, c.b, a);
}
